# Site
repository: DougTrajano/dougresume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Douglas Trajano
title: Data Scientist
email: douglas.trajano@outlook.com
# email_title: Email (Email title override)
phone: +55 51 981988339
# phone_title: Phone (Phone title override)
website: https://dougtrajano.github.io/resume/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: doug_trajano
github_username:  DougTrajano
stackoverflow_username: "8803008"
#dribbble_username: jekyll
facebook_username: DougTrajano
#flickr_username: jekyll
instagram_username: dougtrajano
linkedin_username: douglas-trajano
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: WhatsApp
  icon: fab fa-whatsapp
  url: https://wa.me/5551981988339
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/dougtrajano

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/doug_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I'm Douglas, 27 years old and I live in Canoas, RS, Brazil.

  I'm a data scientist with two years of experience developing amazing <mark>Data Products</mark> and <mark>researches</mark>.
    
  Implementing NLP models, recommendation models, analysis, researches, experiments and A/B tests for customer service.

  As member of the Data Science chapter, I helped define several data science processes used by data scientists across Sicredi (eg. Model Cards, documentations, etc.).

  In my free time, I'm a <mark>CS:GO</mark> and <mark>Age of Empires</mark> player. :)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anallyticabot
        link: https://share.streamlit.io/dougtrajano/anallyticabot/anallyticabot.py
        link_text: Anallyticabot Streamlit
        additional_links:
          - title: DougTrajano/anallyticabot
            icon: fab fa-github
            url: https://github.com/DougTrajano/anallyticabot
        quote: >
          Data App with advanced analytics to improve the quality of chatbots.
        description: | # this will include new lines to allow paragraphs
          **Anallyticabot** is a platform that provides advanced analytics to help you improve your chatbot.

          Identify and improve your virtual assistant's experiences easily and quickly.
    
          Anallyticabot is free to use and is an open source project!
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Cognitivo.ai
        sub_title: Expert Data Scientist
        caption: August 2020 - present
        link: www.cognitivo.ai
        quote: >
          Technology
        description: | # this will include new lines to allow paragraphs
          Project-based work to development and support machine learning enabled solutions for companies in different markets and contexts.
      - layout: left
        title: Sicredi
        sub_title: Cognitive Analyst
        caption: January 2019 - present
        link: www.sicredi.com.br
        quote: >
          Financial Services
        description: | # this will include new lines to allow paragraphs
          Design, development and delivery machine learning enabled solutions for customer service and conversational channels.
      - layout: left
        title: Tivit
        sub_title: IT Process Analyst
        caption: July 2018 - January 2019
        link: www.tivit.com.br
        quote: >
          Technology
        description: | # this will include new lines to allow paragraphs
          Chatbot developer contracted to Sicredi project. Implementation of conversational flows and Python scripts to improve the quality of the chatbot.
      - layout: left
        title: Dell
        sub_title: IT Tech Support Specialist
        caption: April 2015 - July 2018
        link: www.dell.com
        quote: >
          Technology
        description: | # this will include new lines to allow paragraphs
          Development and management of Sprinklr (Social CRM) for Dell's social media teams located in Latin America (Brazil, Costa Rica and Panama).
      - layout: left
        #title: Dell
        sub_title: IT Tech Support Associate
        caption: July 2012 - March 2015
        #link: www.dell.com
        quote: >
          Technology
        description: | # this will include new lines to allow paragraphs
          Technical support for Dell products, customer care for executive escalations with high exposure of brand image.
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Udacity
        sub_title: Nanodegree, Deep Reinforcement Learning
        caption: (2020)
        quote: >
          In Collaboration With: Unity and NVIDIA Deep Learning Institute
        description: | # this will include new lines to allow paragraphs
          Skills Covered
          - Reinforcement Learning
          - Neural Networks
          - PyTorch
          - Deep Q-Networks (DQN)
          - Deep Deterministic Policy Gradients (DDPG)

      - layout: top-left
        title: Udacity
        sub_title: Nanodegree, Data Scientist
        caption: (2019)
        quote: >
          In Collaboration With: Bertelsmann, Figure Eight, IBM Watson, Insight, Kaggle, Starbucks
        description: | # this will include new lines to allow paragraphs
          Skills Covered
          - Machine Learning
          - Deep Learning
          - Software Engineering
          - Applied Data Science

      - layout: top-left
        title: Estácio
        sub_title: BSc, Information Systems
        caption: (2016 - 2019)

  - title: Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Microsoft Certified: Azure Data Scientist Asccoaite <mark>Azure Cloud</mark>
      - AWS Certified Machine Learning - Specialty <mark>AWS</mark>
      - Certified Associate in Project Management (CAPM)® <mark>PMI</mark>
      - ITIL® Foundation Certificate in IT Service Management <mark>EXIN</mark>
      - MCP (70-687) - Configuring Windows 8.1 <mark>Microsoft</mark>
      - Social Media and Community (SMaC) Certification <mark>Dell</mark>
  - title: Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Relevant Courses**
      - Deep Learning Specialization - [deeplearning.ai](https://www.deeplearning.ai/) <mark>Coursera</mark>
      - Machine Learning - [Stanford University](https://www.stanford.edu/) <mark>Coursera</mark>
      - Probability and Statistics: To p or not to p? - [University of London](https://london.ac.uk/) <mark>Coursera</mark>
      - Data Science Math Skills - [Duke University](https://duke.edu/) <mark>Coursera</mark>
      - Creative Thinking: Techniques and Tools for Success - [Imperial College London](https://www.imperial.ac.uk/) <mark>Coursera</mark>
      - Successful Negotiation: Essential Strategies and Skills - [University of Michigan](https://umich.edu/) <mark>Coursera</mark>

      **Others Courses**
      - eXtreme Programming (XP) <mark>TreinaWeb</mark>
      - Design Thinking <mark>TreinaWeb</mark>
      - Tableau for Data Scientists <mark>Udemy</mark>
      - Power BI <mark>Udemy</mark>
      - Python for Data Science and Machine Learning <mark>Udemy</mark>
      - REST APIs with Python and Flask <mark>Udemy</mark>
      - MongoDB Developer <mark>TreinaWeb</mark>
      - MySQL DBA <mark>TreinaWeb</mark>
      - MySQL Developer <mark>TreinaWeb</mark>
      - Oracle Developer <mark>TreinaWeb</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
